name: Check preitter format.
on: push

jobs:
  run_prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: |
          npm install prettier
      - name: Run prettier
        run: |
          npm run prettier --check .
